// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/community-pages/Community.tsx": () => import("../components/mockups/community-pages/Community.tsx"),
  "./components/mockups/community-pages/Events.tsx": () => import("../components/mockups/community-pages/Events.tsx"),
  "./components/mockups/community-pages/Support.tsx": () => import("../components/mockups/community-pages/Support.tsx"),
  "./components/mockups/community-pages/University.tsx": () => import("../components/mockups/community-pages/University.tsx"),
  "./components/mockups/community-pages/Webinars.tsx": () => import("../components/mockups/community-pages/Webinars.tsx"),
  "./components/mockups/community-variations/CommandCenter.tsx": () => import("../components/mockups/community-variations/CommandCenter.tsx"),
  "./components/mockups/community-variations/ConversationFirst.tsx": () => import("../components/mockups/community-variations/ConversationFirst.tsx"),
  "./components/mockups/community-variations/LearningHub.tsx": () => import("../components/mockups/community-variations/LearningHub.tsx"),
  "./components/mockups/community-variations/MobileFirst.tsx": () => import("../components/mockups/community-variations/MobileFirst.tsx")
};
