// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/community-variations/CommandCenter.tsx": () => import("../components/mockups/community-variations/CommandCenter.tsx"),
  "./components/mockups/community-variations/ConversationFirst.tsx": () => import("../components/mockups/community-variations/ConversationFirst.tsx"),
  "./components/mockups/community-variations/LearningHub.tsx": () => import("../components/mockups/community-variations/LearningHub.tsx"),
  "./components/mockups/community-variations/MobileFirst.tsx": () => import("../components/mockups/community-variations/MobileFirst.tsx")
};
